---
# handlers file for ansible-frr
- name: full restart frr
  service:
    name: frr
    state: restarted
    enabled: true
  become: true
  ignore_errors: true
  when: frr_reload != true or _frrdownload.changed
  listen: "restart frr"

- name: reload frr
  service:
    name: frr
    state: reloaded
    enabled: true
  become: true
  ignore_errors: true
  when: frr_reload == true and not _frrdownload.changed
  listen: "restart frr"

- name: start frr
  service:
    name: frr
    state: started
    enabled: true
  become: true
  listen: "start frr"
